### ISSUE TITLE
(Pending) Player specs 

### ISSUE THREAD

**Issue by NinoSkopac** [read2me-online/read2me-widget#10]
# Todo 
- [x] title: explicit or page title by default
- [x] avatar: can be set explicitly or implicitly (only applies to simple c/p player)

## Avatar
- simple c/p player
    - explicitly: use a HTML attribute (eg data-avatar) with either relative or aboslute URL (the latter is recommended)
    - implicitly: omitting the HTML attribute will try getting it automatically
        - try OG: image first
        - R2M default image as a failover
- player constructor code
    - checks if the HTML player has the necessary attribute
        - if it does, use that value
        - if it doesn’t use our function
- if there’s no image found (nothing explicitly set, script didn’t find anything) display a read2me logo (https://read2me.online/images/favicons/android-chrome-192x192.png)

## SDK 
- [x] put it on S3 and CDN it via Cloudfront
- [x] versioning
